default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  # username: postgres
  # password: <%= ENV['PG_PASSWORD'] %>
  database: Budget_app_development

test:
  <<: *default
  database: Budget_app_test

production:
  <<: *default
  url: <% ENV["DATABASE_URL"]%>
